#!/usr/bin/env bash
# Full data download followed by the G0 check (generated by e3sse_bootstrap.sh)
cd "/srv/ben/e3sse"
"/srv/ben/e3sse/.venv/bin/python" scripts/fetch_data.py --root "/srv/ben/e3sse/data" --all
"/srv/ben/e3sse/.venv/bin/python" scripts/check_g0.py --root "/srv/ben/e3sse/data" --mplitrj MPLiTrj_subsample
echo
echo "FINISHED at $(date -u)"
"/srv/ben/e3sse/.venv/bin/python" - <<'PYEOF'
import json
m = json.load(open("/srv/ben/e3sse/data/manifest.json"))
for k, v in m.items():
    print(f"{k:36s} {v['status']}")
bad = [k for k, v in m.items() if v["status"] != "ok"]
print("\nALL DATA OK" if not bad else f"\nNOT OK: {bad}  (re-run: bash /srv/ben/e3sse/scripts/run_download.sh)")
PYEOF
